
package tiket;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class mainWindow extends javax.swing.JFrame {

    int stokkun = 100;
    int stokbir = 100;
    int stokhij = 100;
    int stokmer = 100;
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menuTiket = new javax.swing.JPanel();
        namamenuTiket = new javax.swing.JLabel();
        menuRules = new javax.swing.JPanel();
        namamenuRules = new javax.swing.JLabel();
        menuAbout = new javax.swing.JPanel();
        namamenuAbout = new javax.swing.JLabel();
        menuHistory = new javax.swing.JPanel();
        namamenuHistory = new javax.swing.JLabel();
        ijoPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ijoTiket = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ijoRules = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ijoAbout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ijoHistory = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        isiTiket = new javax.swing.JPanel();
        Pertandingan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Club1 = new javax.swing.JLabel();
        VS = new javax.swing.JLabel();
        Club2 = new javax.swing.JLabel();
        Beli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Datadiri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Selatan = new javax.swing.JRadioButton();
        Barat = new javax.swing.JRadioButton();
        Utara = new javax.swing.JRadioButton();
        Timur = new javax.swing.JRadioButton();
        Pilih = new javax.swing.JButton();
        Harga = new javax.swing.JLabel();
        stokkuning = new javax.swing.JLabel();
        stokbiru = new javax.swing.JLabel();
        stokhijau = new javax.swing.JLabel();
        stokmerah = new javax.swing.JLabel();
        Payment = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        paymentConfirm = new javax.swing.JToggleButton();
        paymentPass = new javax.swing.JPasswordField();
        Success = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        isiRules = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        isiAbout = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        isiHistory = new javax.swing.JPanel();
        loginAdmin = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Salah = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        pilihAdmin = new javax.swing.JPanel();
        matchconfig = new javax.swing.JButton();
        histori = new javax.swing.JButton();
        Tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_history = new javax.swing.JTable();
        Matchconfig = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        home = new javax.swing.JTextField();
        away = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        setsuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/resize-1588520074822892131logopssi.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        menuTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTiketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuTiketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuTiketMouseExited(evt);
            }
        });

        namamenuTiket.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namamenuTiket.setText("  TIKET BOLA");

        javax.swing.GroupLayout menuTiketLayout = new javax.swing.GroupLayout(menuTiket);
        menuTiket.setLayout(menuTiketLayout);
        menuTiketLayout.setHorizontalGroup(
            menuTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTiketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namamenuTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuTiketLayout.setVerticalGroup(
            menuTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namamenuTiket, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menuRules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRulesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuRulesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuRulesMouseExited(evt);
            }
        });

        namamenuRules.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namamenuRules.setText("     RULES");

        javax.swing.GroupLayout menuRulesLayout = new javax.swing.GroupLayout(menuRules);
        menuRules.setLayout(menuRulesLayout);
        menuRulesLayout.setHorizontalGroup(
            menuRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namamenuRules, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuRulesLayout.setVerticalGroup(
            menuRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namamenuRules, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAboutMouseExited(evt);
            }
        });

        namamenuAbout.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namamenuAbout.setText("  ABOUT");

        javax.swing.GroupLayout menuAboutLayout = new javax.swing.GroupLayout(menuAbout);
        menuAbout.setLayout(menuAboutLayout);
        menuAboutLayout.setHorizontalGroup(
            menuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAboutLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namamenuAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        menuAboutLayout.setVerticalGroup(
            menuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namamenuAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menuHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHistoryMouseExited(evt);
            }
        });

        namamenuHistory.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namamenuHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namamenuHistory.setText("ADMIN");

        javax.swing.GroupLayout menuHistoryLayout = new javax.swing.GroupLayout(menuHistory);
        menuHistory.setLayout(menuHistoryLayout);
        menuHistoryLayout.setHorizontalGroup(
            menuHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namamenuHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuHistoryLayout.setVerticalGroup(
            menuHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namamenuHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menuTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(menuRules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(menuHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuRules, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuTiket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ijoPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        ijoPanel.add(jPanel3, "card4");

        ijoTiket.setBackground(new java.awt.Color(0, 106, 65));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BELI TIKET l");

        javax.swing.GroupLayout ijoTiketLayout = new javax.swing.GroupLayout(ijoTiket);
        ijoTiket.setLayout(ijoTiketLayout);
        ijoTiketLayout.setHorizontalGroup(
            ijoTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ijoTiketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        ijoTiketLayout.setVerticalGroup(
            ijoTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        ijoPanel.add(ijoTiket, "card2");

        ijoRules.setBackground(new java.awt.Color(0, 106, 65));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RULES l");

        javax.swing.GroupLayout ijoRulesLayout = new javax.swing.GroupLayout(ijoRules);
        ijoRules.setLayout(ijoRulesLayout);
        ijoRulesLayout.setHorizontalGroup(
            ijoRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ijoRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );
        ijoRulesLayout.setVerticalGroup(
            ijoRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        ijoPanel.add(ijoRules, "card3");

        ijoAbout.setBackground(new java.awt.Color(0, 105, 65));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ABOUT l");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout ijoAboutLayout = new javax.swing.GroupLayout(ijoAbout);
        ijoAbout.setLayout(ijoAboutLayout);
        ijoAboutLayout.setHorizontalGroup(
            ijoAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ijoAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        ijoAboutLayout.setVerticalGroup(
            ijoAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        ijoPanel.add(ijoAbout, "card5");

        ijoHistory.setBackground(new java.awt.Color(0, 105, 65));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HISTORY l");

        javax.swing.GroupLayout ijoHistoryLayout = new javax.swing.GroupLayout(ijoHistory);
        ijoHistory.setLayout(ijoHistoryLayout);
        ijoHistoryLayout.setHorizontalGroup(
            ijoHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ijoHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        ijoHistoryLayout.setVerticalGroup(
            ijoHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        ijoPanel.add(ijoHistory, "card6");

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Welcome..");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel6, "card2");

        isiTiket.setBackground(new java.awt.Color(255, 255, 255));
        isiTiket.setLayout(new java.awt.CardLayout());

        Pertandingan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pertandingan");

        Club1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Club1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Club1.setText("INDONESIA");

        VS.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        VS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS.setText("VS");

        Club2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Club2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Club2.setText("MALAYSIA");

        Beli.setText("Beli Tiket");
        Beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Maguwoharjo International Stadium (MIS)");

        javax.swing.GroupLayout PertandinganLayout = new javax.swing.GroupLayout(Pertandingan);
        Pertandingan.setLayout(PertandinganLayout);
        PertandinganLayout.setHorizontalGroup(
            PertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Club1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Club2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PertandinganLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(Beli)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        PertandinganLayout.setVerticalGroup(
            PertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PertandinganLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Club1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Club2)
                .addGap(18, 18, 18)
                .addComponent(Beli)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        isiTiket.add(Pertandingan, "card2");

        Datadiri.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nama");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/resize-1588914511513386245TIKETTRIBUNTIMURINDONESIAVSICELAND11JANUARI2018STAD_1.jpg"))); // NOI18N

        jLabel6.setText("Pilih Tribun");

        buttonGroup1.add(Selatan);
        Selatan.setText("Selatan (Kuning)");
        Selatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelatanActionPerformed(evt);
            }
        });

        buttonGroup1.add(Barat);
        Barat.setText("VIP Barat (Biru)");
        Barat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaratActionPerformed(evt);
            }
        });

        buttonGroup1.add(Utara);
        Utara.setText("Utara (Hijau)");
        Utara.setToolTipText("");
        Utara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtaraActionPerformed(evt);
            }
        });

        buttonGroup1.add(Timur);
        Timur.setText("Timur (Merah)");
        Timur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimurActionPerformed(evt);
            }
        });

        Pilih.setText("Pilih");
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatadiriLayout = new javax.swing.GroupLayout(Datadiri);
        Datadiri.setLayout(DatadiriLayout);
        DatadiriLayout.setHorizontalGroup(
            DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatadiriLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatadiriLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatadiriLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DatadiriLayout.createSequentialGroup()
                                .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Selatan)
                                    .addComponent(Barat)
                                    .addComponent(Utara)
                                    .addComponent(Timur))
                                .addGap(59, 59, 59)
                                .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stokkuning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stokbiru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stokhijau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stokmerah, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))))
                    .addGroup(DatadiriLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        DatadiriLayout.setVerticalGroup(
            DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatadiriLayout.createSequentialGroup()
                .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatadiriLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Selatan)
                            .addComponent(stokkuning))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Barat)
                            .addComponent(stokbiru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Utara)
                            .addComponent(stokhijau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DatadiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Timur)
                            .addComponent(stokmerah))
                        .addGap(18, 18, 18)
                        .addComponent(Harga)
                        .addGap(18, 18, 18)
                        .addComponent(Pilih))
                    .addGroup(DatadiriLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        isiTiket.add(Datadiri, "card3");

        Payment.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Silahkan bayar melalui loket..");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Admin confirmation");
        jLabel16.setToolTipText("");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Password");
        jLabel17.setToolTipText("");

        paymentConfirm.setText("Confirm");
        paymentConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(paymentConfirm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(paymentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(paymentConfirm)
                .addContainerGap())
        );

        javax.swing.GroupLayout PaymentLayout = new javax.swing.GroupLayout(Payment);
        Payment.setLayout(PaymentLayout);
        PaymentLayout.setHorizontalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PaymentLayout.setVerticalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        isiTiket.add(Payment, "card4");

        Success.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-inspection-50.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Payment Success..");

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuccessLayout = new javax.swing.GroupLayout(Success);
        Success.setLayout(SuccessLayout);
        SuccessLayout.setHorizontalGroup(
            SuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuccessLayout.createSequentialGroup()
                .addGroup(SuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuccessLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SuccessLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SuccessLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jButton1)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        SuccessLayout.setVerticalGroup(
            SuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuccessLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        isiTiket.add(Success, "card5");

        mainPanel.add(isiTiket, "card3");

        isiRules.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("NO RACISM !");

        jLabel23.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("NO FIREWORKS !");

        jLabel24.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("NO FLARE !");

        jLabel25.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("JUST SINGING AND YELLING");

        jLabel26.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("FOR OUR PRIDE");

        javax.swing.GroupLayout isiRulesLayout = new javax.swing.GroupLayout(isiRules);
        isiRules.setLayout(isiRulesLayout);
        isiRulesLayout.setHorizontalGroup(
            isiRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiRulesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                .addContainerGap())
        );
        isiRulesLayout.setVerticalGroup(
            isiRulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiRulesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        mainPanel.add(isiRules, "card4");

        isiAbout.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("For more information, visit www.pssi.org");

        javax.swing.GroupLayout isiAboutLayout = new javax.swing.GroupLayout(isiAbout);
        isiAbout.setLayout(isiAboutLayout);
        isiAboutLayout.setHorizontalGroup(
            isiAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        isiAboutLayout.setVerticalGroup(
            isiAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiAboutLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel27)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        mainPanel.add(isiAbout, "card5");

        isiHistory.setLayout(new java.awt.CardLayout());

        loginAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-admin-settings-male-30.png"))); // NOI18N
        jLabel12.setText(" Login as Admin");

        jLabel11.setText("Username");

        jLabel13.setText("Password");

        Salah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginAdminLayout = new javax.swing.GroupLayout(loginAdmin);
        loginAdmin.setLayout(loginAdminLayout);
        loginAdminLayout.setHorizontalGroup(
            loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAdminLayout.createSequentialGroup()
                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginAdminLayout.createSequentialGroup()
                        .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginAdminLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(Password)))
                            .addGroup(loginAdminLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(Salah, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 191, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(loginAdminLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(Login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginAdminLayout.setVerticalGroup(
            loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAdminLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login)
                .addGap(28, 28, 28)
                .addComponent(Salah)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        isiHistory.add(loginAdmin, "card2");

        pilihAdmin.setBackground(new java.awt.Color(255, 255, 255));

        matchconfig.setText("Match Config");
        matchconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchconfigActionPerformed(evt);
            }
        });

        histori.setText("Histori Pembelian");
        histori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pilihAdminLayout = new javax.swing.GroupLayout(pilihAdmin);
        pilihAdmin.setLayout(pilihAdminLayout);
        pilihAdminLayout.setHorizontalGroup(
            pilihAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihAdminLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(pilihAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(histori, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(matchconfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        pilihAdminLayout.setVerticalGroup(
            pilihAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihAdminLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(histori)
                .addGap(18, 18, 18)
                .addComponent(matchconfig)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        isiHistory.add(pilihAdmin, "card4");

        Tabel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tribun"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_history.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbl_history);

        javax.swing.GroupLayout TabelLayout = new javax.swing.GroupLayout(Tabel);
        Tabel.setLayout(TabelLayout);
        TabelLayout.setHorizontalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        TabelLayout.setVerticalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        isiHistory.add(Tabel, "card3");

        Matchconfig.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("HOME");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("AWAY");

        home.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        home.setText("Indonesia");

        away.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        away.setText("Malaysia");

        jButton2.setText("Set Match");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setsuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setsuccess.setText(".");

        javax.swing.GroupLayout MatchconfigLayout = new javax.swing.GroupLayout(Matchconfig);
        Matchconfig.setLayout(MatchconfigLayout);
        MatchconfigLayout.setHorizontalGroup(
            MatchconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchconfigLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(136, 136, 136))
            .addGroup(MatchconfigLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(away, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MatchconfigLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MatchconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(setsuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(278, 278, 278))
        );
        MatchconfigLayout.setVerticalGroup(
            MatchconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchconfigLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MatchconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatchconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(away, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(setsuccess)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        isiHistory.add(Matchconfig, "card5");

        mainPanel.add(isiHistory, "card6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ijoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ijoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliActionPerformed
        isiTiket.removeAll();
        isiTiket.repaint();
        isiTiket.revalidate();
        
        isiTiket.add(Datadiri);
        isiTiket.repaint();
        isiTiket.revalidate();
        
        stokkuning.setText("Stok = "+stokkun);
        stokbiru.setText("Stok = "+stokbir);
        stokhijau.setText("Stok = "+stokhij);
        stokmerah.setText("Stok = "+stokmer);
    }//GEN-LAST:event_BeliActionPerformed

    private void menuHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoryMouseExited
        menuHistory.setBackground(null);
        namamenuHistory.setForeground(Color.BLACK);
    }//GEN-LAST:event_menuHistoryMouseExited

    private void menuHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoryMouseEntered
        menuHistory.setBackground(Color.GRAY);
        namamenuHistory.setForeground(Color.white);
    }//GEN-LAST:event_menuHistoryMouseEntered

    private void menuHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoryMouseClicked
        ijoPanel.removeAll();
        ijoPanel.repaint();
        ijoPanel.revalidate();

        ijoPanel.add(ijoHistory);
        ijoPanel.repaint();
        ijoPanel.revalidate();
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(isiHistory);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        isiHistory.removeAll();
        isiHistory.repaint();
        isiHistory.revalidate();
        
        isiHistory.add(loginAdmin);
        isiHistory.repaint();
        isiHistory.revalidate();
    }//GEN-LAST:event_menuHistoryMouseClicked

    private void menuAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAboutMouseExited
        menuAbout.setBackground(null);
        namamenuAbout.setForeground(Color.BLACK);
    }//GEN-LAST:event_menuAboutMouseExited

    private void menuAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAboutMouseEntered
        menuAbout.setBackground(Color.GRAY);
        namamenuAbout.setForeground(Color.white);
    }//GEN-LAST:event_menuAboutMouseEntered

    private void menuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAboutMouseClicked
        ijoPanel.removeAll();
        ijoPanel.repaint();
        ijoPanel.revalidate();

        ijoPanel.add(ijoAbout);
        ijoPanel.repaint();
        ijoPanel.revalidate();
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(isiAbout);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_menuAboutMouseClicked

    private void menuRulesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRulesMouseExited
        menuRules.setBackground(null);
        namamenuRules.setForeground(Color.BLACK);
    }//GEN-LAST:event_menuRulesMouseExited

    private void menuRulesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRulesMouseEntered
        menuRules.setBackground(Color.GRAY);
        namamenuRules.setForeground(Color.white);
    }//GEN-LAST:event_menuRulesMouseEntered

    private void menuRulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRulesMouseClicked
        ijoPanel.removeAll();
        ijoPanel.repaint();
        ijoPanel.revalidate();

        ijoPanel.add(ijoRules);
        ijoPanel.repaint();
        ijoPanel.revalidate();
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(isiRules);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_menuRulesMouseClicked

    private void menuTiketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTiketMouseExited
        menuTiket.setBackground(null);
        namamenuTiket.setForeground(Color.BLACK);
    }//GEN-LAST:event_menuTiketMouseExited

    private void menuTiketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTiketMouseEntered
        menuTiket.setBackground(Color.GRAY);
        namamenuTiket.setForeground(Color.white);
    }//GEN-LAST:event_menuTiketMouseEntered

    private void menuTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTiketMouseClicked
        ijoPanel.removeAll();
        ijoPanel.repaint();
        ijoPanel.revalidate();

        ijoPanel.add(ijoTiket);
        ijoPanel.repaint();
        ijoPanel.revalidate();

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(isiTiket);
        mainPanel.repaint();
        mainPanel.revalidate();

        isiTiket.removeAll();
        isiTiket.repaint();
        isiTiket.revalidate();

        isiTiket.add(Pertandingan);
        isiTiket.repaint();
        isiTiket.revalidate();
    }//GEN-LAST:event_menuTiketMouseClicked

    private void SelatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelatanActionPerformed
        Harga.setText("Anda akan membeli tiket Selatan Rp 30.000");
        Harga.getText();
        
    }//GEN-LAST:event_SelatanActionPerformed

    private void BaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaratActionPerformed
        Harga.setText("Anda akan membeli tiket Barat Rp 70.000");
        Harga.getText();
        
    }//GEN-LAST:event_BaratActionPerformed

    private void UtaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtaraActionPerformed
        Harga.setText("Anda akan membeli tiket Utara Rp 30.000");
        Harga.getText();
        
    }//GEN-LAST:event_UtaraActionPerformed

    private void TimurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimurActionPerformed
        Harga.setText("Anda akan membeli tiket Timur Rp 50.000");
        Harga.getText();
        
    }//GEN-LAST:event_TimurActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String user = Username.getText();
        String pass = Password.getText();
        classadmin cek = new classadmin(user, pass);
        cek.checkadmin();
        if (cek.checkadmin()==true){
            isiHistory.removeAll();
            isiHistory.repaint();
            isiHistory.revalidate();

            isiHistory.add(pilihAdmin);
            isiHistory.repaint();
            isiHistory.revalidate();
            
            Username.setText("");
            Password.setText("");
            Salah.setText("");
        }
        else {
            Salah.setText("Username/Password Salah!");            
            Username.setText("");
            Password.setText("");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        
        String namadiri = Nama.getText();
        if (namadiri.equals("")){
            JOptionPane.showMessageDialog(this, "Masukkan nama!");
        }
        
        else {        
                       
            isiTiket.removeAll();
            isiTiket.repaint();
            isiTiket.revalidate();

            isiTiket.add(Payment);
            isiTiket.repaint();
            isiTiket.revalidate();
        }                
        
    }//GEN-LAST:event_PilihActionPerformed

    private void paymentConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentConfirmActionPerformed
        String payment = paymentPass.getText();
        if (payment.equals("12345")){
            isiTiket.removeAll();
            isiTiket.repaint();
            isiTiket.revalidate();

            isiTiket.add(Success);
            isiTiket.repaint();
            isiTiket.revalidate();
            paymentPass.setText("");
            
            if (Selatan.isSelected()){
                DefaultTableModel model= (DefaultTableModel) tbl_history.getModel();
                model.addRow(new Object[]{Nama.getText(),Selatan.getText()});
                this.stokkun-=1;
                stokkuning.setText("");
            }
            else if (Barat.isSelected()){
                DefaultTableModel model= (DefaultTableModel) tbl_history.getModel();
                model.addRow(new Object[]{Nama.getText(),Barat.getText()});
                this.stokbir-=1;
                stokbiru.setText("");
            }
            else if (Utara.isSelected()){
                DefaultTableModel model= (DefaultTableModel) tbl_history.getModel();
                model.addRow(new Object[]{Nama.getText(),Utara.getText()});
                this.stokhij-=1;
                stokhijau.setText("");
            }
            else if (Timur.isSelected()) {
                DefaultTableModel model= (DefaultTableModel) tbl_history.getModel();
                model.addRow(new Object[]{Nama.getText(),Timur.getText()});
                this.stokmer-=1;
                stokmerah.setText("");
            }
            Nama.setText("");
        }
        else {
            JOptionPane.showMessageDialog(this, "Password Salah!");
        }
                       
    }//GEN-LAST:event_paymentConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Club1.setText(home.getText());
        Club2.setText(away.getText());
        setsuccess.setText("Success");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void matchconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchconfigActionPerformed
        isiHistory.removeAll();
        isiHistory.repaint();
        isiHistory.revalidate();

        isiHistory.add(Matchconfig);
        isiHistory.repaint();
        isiHistory.revalidate();
    }//GEN-LAST:event_matchconfigActionPerformed

    private void historiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiActionPerformed
        isiHistory.removeAll();
        isiHistory.repaint();
        isiHistory.revalidate();

        isiHistory.add(Tabel);
        isiHistory.repaint();
        isiHistory.revalidate();
    }//GEN-LAST:event_historiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ijoPanel.removeAll();
        ijoPanel.repaint();
        ijoPanel.revalidate();
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(isiRules);
        mainPanel.repaint();
        mainPanel.revalidate();
      
    }//GEN-LAST:event_jButton1ActionPerformed
                                   

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Barat;
    private javax.swing.JButton Beli;
    private javax.swing.JLabel Club1;
    private javax.swing.JLabel Club2;
    private javax.swing.JPanel Datadiri;
    private javax.swing.JLabel Harga;
    private javax.swing.JButton Login;
    private javax.swing.JPanel Matchconfig;
    private javax.swing.JTextField Nama;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPanel Payment;
    private javax.swing.JPanel Pertandingan;
    private javax.swing.JButton Pilih;
    private javax.swing.JLabel Salah;
    private javax.swing.JRadioButton Selatan;
    private javax.swing.JPanel Success;
    private javax.swing.JPanel Tabel;
    private javax.swing.JRadioButton Timur;
    private javax.swing.JTextField Username;
    private javax.swing.JRadioButton Utara;
    private javax.swing.JLabel VS;
    private javax.swing.JTextField away;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton histori;
    private javax.swing.JTextField home;
    private javax.swing.JPanel ijoAbout;
    private javax.swing.JPanel ijoHistory;
    private javax.swing.JPanel ijoPanel;
    private javax.swing.JPanel ijoRules;
    private javax.swing.JPanel ijoTiket;
    private javax.swing.JPanel isiAbout;
    private javax.swing.JPanel isiHistory;
    private javax.swing.JPanel isiRules;
    private javax.swing.JPanel isiTiket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loginAdmin;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton matchconfig;
    private javax.swing.JPanel menuAbout;
    private javax.swing.JPanel menuHistory;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel menuRules;
    private javax.swing.JPanel menuTiket;
    private javax.swing.JLabel namamenuAbout;
    private javax.swing.JLabel namamenuHistory;
    private javax.swing.JLabel namamenuRules;
    private javax.swing.JLabel namamenuTiket;
    private javax.swing.JToggleButton paymentConfirm;
    private javax.swing.JPasswordField paymentPass;
    private javax.swing.JPanel pilihAdmin;
    private javax.swing.JLabel setsuccess;
    private javax.swing.JLabel stokbiru;
    private javax.swing.JLabel stokhijau;
    private javax.swing.JLabel stokkuning;
    private javax.swing.JLabel stokmerah;
    private javax.swing.JTable tbl_history;
    // End of variables declaration//GEN-END:variables
}
